spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # sout을 통해 로깅
        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#        default_batch_fetch_size: 100 # batch size 설정
#    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true

logging:
  level:
    org.hibernate.SQL: debug # logger 통해 로깅
#    org.hibernate.type: trace