apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # StorageClass 상에서 namespace 불필요 (전역적으로 적용되는 대상)
  name: local-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
