apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
  namespace: sns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-volume-claim
      containers:
        - name: image-container
          image: "[ECR]/image-server:0.0.3"
          volumeMounts:
            - mountPath: /images
              name: image-volume
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: IMAGE_PATH
              value: images
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          resources:
            # 처음 띄울 때는 낮춰서
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 10" ]
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 7