server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200

spring:
  data:
    redis:
      # 같은 namespace에 있을 때는 name으로만 접근 가능
      # 다른 namespace 같은 경우 아래 처럼 풀네임 적어줘야 한다.
      host: redis-service.default.svc.cluster.local
      port: 6379

  lifecycle:
    timeout-per-shutdown-phase: 50s

logging:
  file:
    name: /var/log/app/factorial.log
