spring:
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: redis-service.default.svc.cluster.local
      port: 6379
