spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: # spring batch metadata tables

  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    # JPA 기준 초기화 실행시 spring 2.5 이상 버전인 경우 true 설정해야 함
    # (@Entity 기준으로 DDL 생성)
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: false
  sql:
    init:
      mode: embedded # 최초 table 생성할 때만
      data-locations: sql/person.sql

logging:
  level:
    org.hibernate.SQL: debug # logger 통해 로깅
#    org.hibernate.type: trace