spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: beaniejoy
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: never
