spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # JPQL 쿼리를 볼 수 있다.
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
